In [3]:
import numpy as np

In [4]:
print(np.zeros(10))

print(np.zeros((5,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
a = np.zeros((10,3))
b = np.zeros(5)

# print(a)

print(a.shape)

print(a.ndim)
print(b.ndim)

print(a.size)

(10, 3)
2
1
30


In [6]:
print(type(np.zeros(5)))

<class 'numpy.ndarray'>


In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.full((2,3,4), 4)

array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [9]:
def full(shape, fill_value):
    pass

full((3,2), 10)

full(fill_value=10, shape=(3,2))

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# sampe ravel

In [12]:
a = np.zeros((2,3,4))

a.shape

(2, 3, 4)

In [15]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

a * b

array([ 1,  4,  9, 16, 25])

In [17]:
try:
    print("Hello")
except ValueError as e:
    print(e)

Hello


In [28]:
m = np.array([10,20,30,40])

arr = np.array([[1,2,3],
                [4,5,6]])

print(m.mean())


25.0


In [36]:
a = np.arange(40).reshape(2,5,4)

print(a[0,0,1])


1


In [42]:
a[0,0,0] = 10
for i in a.flat:
    print(i)

10
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


In [53]:
a = np.array([[1,10,5,3],[2,3,2,1]])
b = np.array([[3,4,1,0],[1,2,3,4]])

print(a*b)

[[ 3 40  5  0]
 [ 2  6  6  4]]


In [ ]:
import numpy.linalg as linalg



In [58]:
a = np.random.rand(2,3)

np.save("my_array", a)